name: 'Docs Build'

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - 'docs/**'
    - '.github/**/*docs*'
  pull_request:
    paths:
    - 'docs/**'
    - '.github/**/*docs*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  docs:
    name: GitHub Pages
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile
      BUNDLE_PATH: vendor/bundle
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - name: Set up Ruby
      uses: ruby/setup-ruby@5f19ec79cedfadb78ab837f95b87734d0003c899
      with:
        ruby-version: 2.7
        bundler-cache: true
        working-directory: docs
    - name: Build
      run: |
        ./.github/scripts/docs.sh
