name: 'Docs Build'

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - 'docs/**'
    - '.github/**/*docs*'
  pull_request:
    paths:
    - 'docs/**'
    - '.github/**/*docs*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  docs:
    name: GitHub Pages
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile
      BUNDLE_PATH: vendor/bundle
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - name: Set up Ruby
      uses: ruby/setup-ruby@6615b4b8a02c78c4d711c06df4b8a20aa685a45d
      with:
        ruby-version: 2.7
        bundler-cache: true
        working-directory: docs
    - name: Build
      run: |
        ./.github/scripts/docs.sh
