name: 'Wrapper'

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - 'gradle/wrapper/**'
    - 'gradlew*'
    - '.github/**/*wrapper*'
  pull_request:
    paths:
    - 'gradle/wrapper/**'
    - 'gradlew*'
    - '.github/**/*wrapper*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  validate:
    name: Validate Gradle Wrapper
    runs-on: 'ubuntu-latest'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@216d1ad2b3710bf005dc39237337b9673fd8fcd5
