name: 'Wrapper'

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - 'gradle/wrapper/**'
    - 'gradlew*'
    - '.github/**/*wrapper*'
  pull_request:
    paths:
    - 'gradle/wrapper/**'
    - 'gradlew*'
    - '.github/**/*wrapper*'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  validate:
    name: Validate Gradle Wrapper
    runs-on: 'ubuntu-latest'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@5188e9b5527a0a094cee21e2fe9a8ca44b4629af
